### ISSUE TITLE
有异常报错

### ISSUE THREAD

**Issue by GavinOUYANG** [xyc2690/Raspberry_ObjectDetection_Camera#2]
Loading...
Finish Load Graph..
Running detection..
Traceback (most recent call last):
  File "opencv_camera.py", line 88, in <module>
    feed_dict={image_tensor: image_np_expanded})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1089, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: long() argument must be a string or a number, not 'NoneType'

不知道这样要怎样修改

**Comment by wang1051992187** [comment]
同样报这个错误

**Comment by ingod** [comment]
> 同样报这个错误

你解决了吗，参照https://stackoverflow.com/questions/48088283/typeerror-long-argument-must-be-a-string-or-a-number-not-nonetype这个还是不行

**Comment by wang1051992187** [comment]
已经解决
# Set initial frame size.
frameSize = (640, 480)

# Initialize mutithreading the video stream.
cap = VideoStream(src=0, usePiCamera=usingPiCamera, resolution=frameSize,
                 framerate=32).start()
# Allow the camera to warm up.
time.sleep(2.0)


# Init camera
#cap = cv2.VideoCapture(0)
# cap.set(3, 640)  # set Width
# cap.set(4, 480)  # set Height

**Comment by CTQ2333** [comment]
> > 同样报这个错误
> 
> 你解决了吗，参照[https://stackoverflow.com/questions/48088283/typeerror-long-argument-must-be-a-string-or-a-number-not-nonetype这个还是不行](https://stackoverflow.com/questions/48088283/typeerror-long-argument-must-be-a-string-or-a-number-not-nonetype%E8%BF%99%E4%B8%AA%E8%BF%98%E6%98%AF%E4%B8%8D%E8%A1%8C)
你好，请问这个错误解决了吗？我除了这个报错前面好多了两行报错，求教

Loading...
Finish Load Graph..
libv4l2: error turning on stream: Invalid argument
VIDIOC_STREAMON: Invalid argument
Running detection..
Traceback (most recent call last):
  File "opencv_camera.py", line 87, in <module>
    feed_dict={image_tensor: image_np_expanded}) 
  File "/home/pi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/pi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1104, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/pi/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: long() argument must be a string or a number, not 'NoneType'
pi@raspberrypi:~/Raspberry_ObjectDetection_Camera $
